name: Build on Linux (x86_64)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          python3 -m pip install compiledb

      - name: Build all
        run: |
          make all

      - name: Generate compile_commands
        run: |
          make compiledb